// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    VanLoading: typeof import('vant/es')['Loading']
    VanSpace: typeof import('vant/es')['Space']
  }
}

export { }
